"""Delete column query and url in Metrics tables

Revision ID: 54583e7252cc
Revises: b73f9405c347
Create Date: 2024-10-07 21:41:50.156186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54583e7252cc'
down_revision = 'b73f9405c347'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metrics', 'url')
    op.drop_column('metrics_query', 'query')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('url', sa.String(), nullable=False))
    op.add_column('metrics_query', sa.Column('query', sa.String(), nullable=False))
    # ### end Alembic commands ###
