"""add user relation to list autoupdate

Revision ID: 1d0e44087d2d
Revises: 292230311e1f
Create Date: 2024-10-03 15:44:25.594040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d0e44087d2d'
down_revision: Union[str, None] = '292230311e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_search_list_auto_update_schedule', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key("user_fk", 'live_search_list_auto_update_schedule', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_fk", 'live_search_list_auto_update_schedule', type_='foreignkey')
    op.drop_column('live_search_list_auto_update_schedule', 'user_id')
    # ### end Alembic commands ###
