"""Add id_author in Group

Revision ID: 3d33bdef2e5f
Revises: 503ffc00b25f
Create Date: 2024-10-03 20:13:22.940879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d33bdef2e5f'
down_revision: Union[str, None] = '503ffc00b25f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('id_author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'group', 'user', ['id_author'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('user_id_seq'::regclass)"))
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'id_author')
    # ### end Alembic commands ###
