"""add_column_id_author

Revision ID: 645aceed0889
Revises: ef7bf8530baf
Create Date: 2024-10-01 21:00:33.594937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '645aceed0889'
down_revision: Union[str, None] = 'ef7bf8530baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('id_author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'config', 'user', ['id_author'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'config', type_='foreignkey')
    op.drop_column('config', 'id_author')
    # ### end Alembic commands ###
