"""revert_changers_user_id

Revision ID: ef7bf8530baf
Revises: de5b94dcc881
Create Date: 2024-10-01 20:54:07.843003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7bf8530baf'
down_revision: Union[str, None] = 'de5b94dcc881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('config', 'user_id')
    # ### end Alembic commands ###
